/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConvForm: typeof import('./src/components/ConvForm.vue')['default']
    Drag: typeof import('./src/components/Drag.vue')['default']
    Drag2: typeof import('./src/components/Drag2.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    InputSizeForm: typeof import('./src/components/InputSizeForm.vue')['default']
    MaxPoolForm: typeof import('./src/components/MaxPoolForm.vue')['default']
    UserForm: typeof import('./src/components/UserForm.vue')['default']
  }
}
